// 114 Surahs of the Quran
export const SURAHS = [
    { number: 1, name: "Al-Fatiha", nameAr: "الفاتحة", verses: 7 },
    { number: 2, name: "Al-Baqarah", nameAr: "البقرة", verses: 286 },
    { number: 3, name: "Aal-E-Imran", nameAr: "آل عمران", verses: 200 },
    { number: 4, name: "An-Nisa", nameAr: "النساء", verses: 176 },
    { number: 5, name: "Al-Maidah", nameAr: "المائدة", verses: 120 },
    { number: 6, name: "Al-Anam", nameAr: "الأنعام", verses: 165 },
    { number: 7, name: "Al-Araf", nameAr: "الأعراف", verses: 206 },
    { number: 8, name: "Al-Anfal", nameAr: "الأنفال", verses: 75 },
    { number: 9, name: "At-Tawbah", nameAr: "التوبة", verses: 129 },
    { number: 10, name: "Yunus", nameAr: "يونس", verses: 109 },
    { number: 11, name: "Hud", nameAr: "هود", verses: 123 },
    { number: 12, name: "Yusuf", nameAr: "يوسف", verses: 111 },
    { number: 13, name: "Ar-Rad", nameAr: "الرعد", verses: 43 },
    { number: 14, name: "Ibrahim", nameAr: "إبراهيم", verses: 52 },
    { number: 15, name: "Al-Hijr", nameAr: "الحجر", verses: 99 },
    { number: 16, name: "An-Nahl", nameAr: "النحل", verses: 128 },
    { number: 17, name: "Al-Isra", nameAr: "الإسراء", verses: 111 },
    { number: 18, name: "Al-Kahf", nameAr: "الكهف", verses: 110 },
    { number: 19, name: "Maryam", nameAr: "مريم", verses: 98 },
    { number: 20, name: "Ta-Ha", nameAr: "طه", verses: 135 },
    { number: 21, name: "Al-Anbiya", nameAr: "الأنبياء", verses: 112 },
    { number: 22, name: "Al-Hajj", nameAr: "الحج", verses: 78 },
    { number: 23, name: "Al-Muminun", nameAr: "المؤمنون", verses: 118 },
    { number: 24, name: "An-Nur", nameAr: "النور", verses: 64 },
    { number: 25, name: "Al-Furqan", nameAr: "الفرقان", verses: 77 },
    { number: 26, name: "Ash-Shuara", nameAr: "الشعراء", verses: 227 },
    { number: 27, name: "An-Naml", nameAr: "النمل", verses: 93 },
    { number: 28, name: "Al-Qasas", nameAr: "القصص", verses: 88 },
    { number: 29, name: "Al-Ankabut", nameAr: "العنكبوت", verses: 69 },
    { number: 30, name: "Ar-Rum", nameAr: "الروم", verses: 60 },
    { number: 31, name: "Luqman", nameAr: "لقمان", verses: 34 },
    { number: 32, name: "As-Sajdah", nameAr: "السجدة", verses: 30 },
    { number: 33, name: "Al-Ahzab", nameAr: "الأحزاب", verses: 73 },
    { number: 34, name: "Saba", nameAr: "سبأ", verses: 54 },
    { number: 35, name: "Fatir", nameAr: "فاطر", verses: 45 },
    { number: 36, name: "Yasin", nameAr: "يس", verses: 83 },
    { number: 37, name: "As-Saffat", nameAr: "الصافات", verses: 182 },
    { number: 38, name: "Sad", nameAr: "ص", verses: 88 },
    { number: 39, name: "Az-Zumar", nameAr: "الزمر", verses: 75 },
    { number: 40, name: "Ghafir", nameAr: "غافر", verses: 85 },
    { number: 41, name: "Fussilat", nameAr: "فصلت", verses: 54 },
    { number: 42, name: "Ash-Shura", nameAr: "الشورى", verses: 53 },
    { number: 43, name: "Az-Zukhruf", nameAr: "الزخرف", verses: 89 },
    { number: 44, name: "Ad-Dukhan", nameAr: "الدخان", verses: 59 },
    { number: 45, name: "Al-Jathiyah", nameAr: "الجاثية", verses: 37 },
    { number: 46, name: "Al-Ahqaf", nameAr: "الأحقاف", verses: 35 },
    { number: 47, name: "Muhammad", nameAr: "محمد", verses: 38 },
    { number: 48, name: "Al-Fath", nameAr: "الفتح", verses: 29 },
    { number: 49, name: "Al-Hujurat", nameAr: "الحجرات", verses: 18 },
    { number: 50, name: "Qaf", nameAr: "ق", verses: 45 },
    { number: 51, name: "Adh-Dhariyat", nameAr: "الذاريات", verses: 60 },
    { number: 52, name: "At-Tur", nameAr: "الطور", verses: 49 },
    { number: 53, name: "An-Najm", nameAr: "النجم", verses: 62 },
    { number: 54, name: "Al-Qamar", nameAr: "القمر", verses: 55 },
    { number: 55, name: "Ar-Rahman", nameAr: "الرحمن", verses: 78 },
    { number: 56, name: "Al-Waqiah", nameAr: "الواقعة", verses: 96 },
    { number: 57, name: "Al-Hadid", nameAr: "الحديد", verses: 29 },
    { number: 58, name: "Al-Mujadila", nameAr: "المجادلة", verses: 22 },
    { number: 59, name: "Al-Hashr", nameAr: "الحشر", verses: 24 },
    { number: 60, name: "Al-Mumtahanah", nameAr: "الممتحنة", verses: 13 },
    { number: 61, name: "As-Saf", nameAr: "الصف", verses: 14 },
    { number: 62, name: "Al-Jumuah", nameAr: "الجمعة", verses: 11 },
    { number: 63, name: "Al-Munafiqun", nameAr: "المنافقون", verses: 11 },
    { number: 64, name: "At-Taghabun", nameAr: "التغابن", verses: 18 },
    { number: 65, name: "At-Talaq", nameAr: "الطلاق", verses: 12 },
    { number: 66, name: "At-Tahrim", nameAr: "التحريم", verses: 12 },
    { number: 67, name: "Al-Mulk", nameAr: "الملك", verses: 30 },
    { number: 68, name: "Al-Qalam", nameAr: "القلم", verses: 52 },
    { number: 69, name: "Al-Haqqah", nameAr: "الحاقة", verses: 52 },
    { number: 70, name: "Al-Maarij", nameAr: "المعارج", verses: 44 },
    { number: 71, name: "Nuh", nameAr: "نوح", verses: 28 },
    { number: 72, name: "Al-Jinn", nameAr: "الجن", verses: 28 },
    { number: 73, name: "Al-Muzzammil", nameAr: "المزمل", verses: 20 },
    { number: 74, name: "Al-Muddaththir", nameAr: "المدثر", verses: 56 },
    { number: 75, name: "Al-Qiyamah", nameAr: "القيامة", verses: 40 },
    { number: 76, name: "Al-Insan", nameAr: "الإنسان", verses: 31 },
    { number: 77, name: "Al-Mursalat", nameAr: "المرسلات", verses: 50 },
    { number: 78, name: "An-Naba", nameAr: "النبأ", verses: 40 },
    { number: 79, name: "An-Naziat", nameAr: "النازعات", verses: 46 },
    { number: 80, name: "Abasa", nameAr: "عبس", verses: 42 },
    { number: 81, name: "At-Takwir", nameAr: "التكوير", verses: 29 },
    { number: 82, name: "Al-Infitar", nameAr: "الانفطار", verses: 19 },
    { number: 83, name: "Al-Mutaffifin", nameAr: "المطففين", verses: 36 },
    { number: 84, name: "Al-Inshiqaq", nameAr: "الانشقاق", verses: 25 },
    { number: 85, name: "Al-Buruj", nameAr: "البروج", verses: 22 },
    { number: 86, name: "At-Tariq", nameAr: "الطارق", verses: 17 },
    { number: 87, name: "Al-Ala", nameAr: "الأعلى", verses: 19 },
    { number: 88, name: "Al-Ghashiyah", nameAr: "الغاشية", verses: 26 },
    { number: 89, name: "Al-Fajr", nameAr: "الفجر", verses: 30 },
    { number: 90, name: "Al-Balad", nameAr: "البلد", verses: 20 },
    { number: 91, name: "Ash-Shams", nameAr: "الشمس", verses: 15 },
    { number: 92, name: "Al-Layl", nameAr: "الليل", verses: 21 },
    { number: 93, name: "Ad-Duha", nameAr: "الضحى", verses: 11 },
    { number: 94, name: "Ash-Sharh", nameAr: "الشرح", verses: 8 },
    { number: 95, name: "At-Tin", nameAr: "التين", verses: 8 },
    { number: 96, name: "Al-Alaq", nameAr: "العلق", verses: 19 },
    { number: 97, name: "Al-Qadr", nameAr: "القدر", verses: 5 },
    { number: 98, name: "Al-Bayyinah", nameAr: "البينة", verses: 8 },
    { number: 99, name: "Az-Zalzalah", nameAr: "الزلزلة", verses: 8 },
    { number: 100, name: "Al-Adiyat", nameAr: "العاديات", verses: 11 },
    { number: 101, name: "Al-Qariah", nameAr: "القارعة", verses: 11 },
    { number: 102, name: "At-Takathur", nameAr: "التكاثر", verses: 8 },
    { number: 103, name: "Al-Asr", nameAr: "العصر", verses: 3 },
    { number: 104, name: "Al-Humazah", nameAr: "الهمزة", verses: 9 },
    { number: 105, name: "Al-Fil", nameAr: "الفيل", verses: 5 },
    { number: 106, name: "Quraysh", nameAr: "قريش", verses: 4 },
    { number: 107, name: "Al-Maun", nameAr: "الماعون", verses: 7 },
    { number: 108, name: "Al-Kawthar", nameAr: "الكوثر", verses: 3 },
    { number: 109, name: "Al-Kafirun", nameAr: "الكافرون", verses: 6 },
    { number: 110, name: "An-Nasr", nameAr: "النصر", verses: 3 },
    { number: 111, name: "Al-Masad", nameAr: "المسد", verses: 5 },
    { number: 112, name: "Al-Ikhlas", nameAr: "الإخلاص", verses: 4 },
    { number: 113, name: "Al-Falaq", nameAr: "الفلق", verses: 5 },
    { number: 114, name: "An-Nas", nameAr: "الناس", verses: 6 },
] as const;

export const BADGE_DEFINITIONS = [
    {
        id: "first-surah",
        name: "First Surah",
        nameAr: "أول سورة",
        description: "Memorized your first surah",
        descriptionAr: "حفظت أول سورة",
        icon: "🌱",
        type: "MEMORIZATION_MILESTONE",
    },
    {
        id: "juz-amma",
        name: "Juz Amma",
        nameAr: "جزء عمّ",
        description: "Completed Juz Amma (30th Juz)",
        descriptionAr: "أتممت الجزء الثلاثين",
        icon: "⭐",
        type: "MEMORIZATION_MILESTONE",
    },
    {
        id: "streak-7",
        name: "Week Warrior",
        nameAr: "محارب الأسبوع",
        description: "7-day attendance streak",
        descriptionAr: "حضور متواصل لسبعة أيام",
        icon: "🔥",
        type: "STREAK",
    },
    {
        id: "streak-30",
        name: "Month Master",
        nameAr: "سيد الشهر",
        description: "30-day attendance streak",
        descriptionAr: "حضور متواصل لثلاثين يوماً",
        icon: "💎",
        type: "STREAK",
    },
    {
        id: "excellent-eval",
        name: "Excellence",
        nameAr: "التميز",
        description: "Received an Excellent evaluation",
        descriptionAr: "حصلت على تقييم ممتاز",
        icon: "🏆",
        type: "EVALUATION",
    },
] as const;

export const ROLES = ["ADMIN", "TEACHER", "STUDENT", "PARENT"] as const;
export const LOCALES = ["fr", "ar"] as const;
